language: cpp
dist: trusty
sudo: required
os: linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

  #-- Configure Git (needed by YCM)
  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

install:
  #-- Install YARP and KDL deps
  - sudo apt-get install libeigen3-dev # Needed for creating YARP lib_math

  #-- Install OpenRAVE deps
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libqt4-dev qt4-dev-tools libxml2-dev libode-dev # libfcl-dev not on Trusty used in this travis
  - sudo apt-get install libsoqt4-dev libcoin80-dev

  #-- Install ROBOTICSLAB deps
  - sudo apt-get install libspnav-dev libxwiimote-dev

before_script:
  - mkdir build && cd "$_"
  - cmake ..

script:
  - make

after_success:
  - sudo make install
  - sudo make uninstall
