language: cpp
dist: trusty
os: linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    # YARP and KDL
    - libeigen3-dev

    # OpenRAVE
    - libboost-all-dev
    - libqt4-dev
    - qt4-dev-tools
    - libxml2-dev
    - libode-dev
    - libsoqt4-dev
    - libcoin80-dev

    # ROBOTICSLAB
    - libspnav-dev

before_install:
  #-- Configure Git (needed by YCM)
  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

install:
  #-- Install ROBOTICSLAB deps
  - sudo apt-get install libxwiimote-dev

before_script:
  - mkdir build && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install-system"

script:
  - make install

after_success:
  - make uninstall
